### ISSUE TITLE
Issue to get connected to any synthesizer on iPhone

### ISSUE THREAD

**Issue by ekawahyu** [joebowbeer/nRF52FS#1]
I am having trouble to get this connected to any synthesizer app on iPhone, but I can get connected just fine on RF Connect and BLE Scanner. Any recommendation on how to debug this issue? Is iOS supported? Thank you.

**Comment by joebowbeer** [comment]
This did work with iOS and AFAIK still does. I use the free [midimittr](https://github.com/sieren/midimittr) app to debug Bluetooth connections. You should see the device in midimittr’s Devices list and you should be able to connect.

Note that clients can only connect to one host at a time, so be sure to disconnect from any other app first.

Let me know if you continue to have problems, and I’ll try to replicate.

**Comment by ekawahyu** [comment]
I also have midimittr and it does not seem to connect at all. It is an infinite `Connecting...` and then it turns into `Not Connected` after a few minutes. It is iPhone 6S, iOS 13.3.

This is my first time trying BLE Midi, if there is anything I can help to debug, please let me know.

**Comment by joebowbeer** [comment]
I just powered up nRF52Pipe (sparkfun nRF52832 Breakout) and it connected to an iPad running iOS 13.3. It has the same bleSetup as this sketch.

https://github.com/joebowbeer/nRF52Pipe

**Comment by ekawahyu** [comment]
hmm... in theory, this should work on my iPhone with the same iOS version. Ok, will look into the other repo and give it a try.

**Comment by ekawahyu** [comment]
I reinstalled and cleaned my Arduino IDE and it seems to work fine now. Closing this issue, sorry for the trouble.
